---
title: "Nitinat in-season"
date: 'Last update: `r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=F, message=F)


# Load packages ---------------------------------
library(tidyverse)
library(readxl)
library(here)
library(stringr)


# Helpers --------------------------------- <<<UPDATE>>>
escapement_year <- 2023


# ================== READ DATA ================== 
# SIL data ---------------------------------
nitinat.SIL <- readxl::read_excel(path=paste0("//dcbcpbsna01a.ENT.dfo-mpo.ca/SCD_Stad/WCVI/ESCAPEMENT/Data/", 
                                              escapement_year, 
                                              "/SILs/Area 21-22/Nitinat River/A22_Nitinat_River_", 
                                              escapement_year, 
                                              ".xlsx"),
                                  sheet="Nitinat River raw SIL entry", guess_max=1000) %>% 
  mutate_if(is.numeric, ~replace_na(., 0)) %>% 
  mutate_at(c("adults # holding", "adults live / habitat seen (# Est Live)"), ~round(.,0)) %>% 
  mutate(date = lubridate::ymd(date)) %>%
  print()


# Water data ---------------------------------
nitinat.water <- lapply(list.files(path = here("data"),
                                   pattern = "^NitinatWaterLevelHydrometData.*\\.xlsx$",
                                   full.names = TRUE), 
                        readxl::read_excel, sheet="Exported Data") %>% 
  do.call("cbind",.) %>%
  mutate(time = stringr::str_sub(Time, 12, 19),
         date = as.Date(stringr::str_sub(Time,1,11))) %>%
  mutate_at("Staff Gauge(mH20)", as.numeric) %>%
  rename(DateTime = Time) %>%
  print()



# Historical SIL data ---------------------------------
rtTabs <- readxl::read_excel("//dcbcpbsna01a.ENT.dfo-mpo.ca/SCD_Stad/WCVI/ESCAPEMENT/Data/run timing tables (updated).xlsx", sheet="nitinat_Rfriendly") %>% 
  pivot_longer(cols=c(`81`:`124`), names_to="stat_week", values_to="count") %>%
  print()
rtTabs$stat_week <- factor(rtTabs$stat_week, levels=c("81","82","83","84","91","92","93","94","101","102","103","104","105",
                                                              "111","112","113","114","115","121","122","123","124", ordered=T))
```


The `r escapement_year` Nitinat River and tribs surveys began on `r min(nitinat.SIL[!is.na(nitinat.SIL$date),]$date)`. The most recent survey to date is `r max(nitinat.SIL[!is.na(nitinat.SIL$date),]$date)`. 

<br>

# Live and dead totals 

<br> 

```{r}
ggplot() +
  geom_point(data=nitinat.SIL %>% 
               filter(system=="Nitinat River") %>% 
               group_by(date, species) %>% 
               summarize(total_adults_ded=sum(`adults dead`)) , 
             aes(x=date, y=total_adults_ded*10, group=species, colour=species)) +
  geom_line(data=nitinat.SIL %>% 
              filter(system=="Nitinat River") %>% 
              group_by(date, species) %>% 
              summarize(total_adults_ded=sum(`adults dead`)), 
            aes(x=date, y=total_adults_ded*10, group=species, colour=species)) +
  
  geom_bar(data=nitinat.SIL %>% 
             filter(system=="Nitinat River") %>% 
             group_by(date, species) %>% 
             summarize(total_adults=sum(`adults live / habitat seen (# Est Live)`)), 
           aes(x=date, y=total_adults, group=species, fill=species), stat="identity", alpha=0.8) +
  facet_wrap(~species, scales="free") +
  scale_x_date(date_breaks="7 day", date_labels = "%b %d") +
  scale_y_continuous(sec.axis = sec_axis(~ . /100, name = "total dead adults (LINE)")) +
  labs(x="", y="total live adults (BAR)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle=45, hjust=1),
        legend.position = "none")
```

<br>

<br>

# Focal species live ~ historical 

```{r}
ggplot() +
  geom_bar(data=rtTabs %>% filter(Year<escapement_year),
           aes(x=stat_week, y=count, group=Year), stat="identity", position="identity", alpha=0.2, fill="gray40") +
  geom_bar(data=rtTabs %>% filter(Year==escapement_year),
           aes(x=stat_week, y=count, group=Year), stat="identity", position="identity", alpha=0.6, fill="dodger blue") +  
  facet_wrap(~species, scales="free") +
  labs(x="", y="total live adults") +
  theme_bw() +
  theme(axis.text = element_text(size=12),
        legend.position = "none")
```

<br>

<br>


# Live ~ water 

```{r}
ggplot() +
  geom_line(data=nitinat.water %>% 
              group_by(date) %>% 
              summarize(mean_water = mean(`Staff Gauge(mH20)`), min=min(`Staff Gauge(mH20)`), max=max(`Staff Gauge(mH20)`)),
            aes(x=date, y=mean_water*1000), colour="dodger blue", size=1) +
  
  geom_ribbon(data=nitinat.water %>% 
              group_by(date) %>% 
              summarize(mean_water = mean(`Staff Gauge(mH20)`), min=min(`Staff Gauge(mH20)`), max=max(`Staff Gauge(mH20)`)),
            aes(x=date, ymin=min*1000, ymax=max*1000), fill="dodger blue", alpha=0.6) +
  
  geom_bar(data=nitinat.SIL %>% 
             filter(system=="Nitinat River", species%in%c("Chinook", "Chum", "Coho")) %>% 
             group_by(date, species) %>% 
             summarize(total_adults=sum(`adults live / habitat seen (# Est Live)`)), 
           aes(x=date, y=total_adults, group=species, fill=species), stat="identity", alpha=0.8) +
  
  scale_x_date(date_breaks="7 day", date_labels = "%b %d") +
  scale_y_continuous(sec.axis = sec_axis(~ . /1000, name = "water level (m)")) +
  
  theme_bw() +
  theme(axis.text.x = element_text(angle=45, hjust=1),
        legend.position = "none") +
  facet_wrap(~species, scales="free")
```









